<a href="https://colab.research.google.com/github/sripilla/deep-learning-course-notes/blob/main/02_Tensors_and_Multidimensional_Arrays/05_matrix_multiplication/torch_matmul.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import torch

tensor_A = torch.rand(size=(2,3))
tensor_B = torch.rand(size=(2,3))

# This will FAIL, Matrix multiplication ≠ Element-wise multiplication
# torch.matmul(tensor_A, tensor_B)

# Fix using transpose
tensor_C = torch.matmul(tensor_A, tensor_B.T)
print(tensor_C)

"""
Use: torch.matmul() or @
Rule:
(𝑚×𝑛)(𝑛×𝑝)=(𝑚×𝑝)
(m×n)(n×p)=(m×p)
Condition:
👉 cols(A) == rows(B)
If shapes mismatch:
👉 Use transpose → B.T
Example:
(2×3) × (2×3) ❌ → (2×3) × (3×2) ✅ → (2×2)
Important:
👉 * = element-wise ❌
👉 matmul / @ = matrix multiplication ✅
Methods:
mm() → only 2D
matmul() → all cases
bmm() → batch
@ → clean syntax
Core idea:
👉 Rows × Columns → dot product
"""


tensor([[0.5655, 0.9766],
        [0.3544, 0.6586]])


'\nUse: torch.matmul() or @\nRule:\n(𝑚×𝑛)(𝑛×𝑝)=(𝑚×𝑝)\n(m×n)(n×p)=(m×p)\nCondition:\n👉 cols(A) == rows(B)\nIf shapes mismatch:\n👉 Use transpose → B.T\nExample:\n(2×3) × (2×3) ❌ → (2×3) × (3×2) ✅ → (2×2)\nImportant:\n👉 * = element-wise ❌\n👉 matmul / @ = matrix multiplication ✅\nMethods:\nmm() → only 2D\nmatmul() → all cases\nbmm() → batch\n@ → clean syntax\nCore idea:\n👉 Rows × Columns → dot product\n'

In [1]:
import torch

# -------------------------------
# 🔹 1. Vector × Vector (Dot Product)
# -------------------------------
a = torch.tensor([1., 2., 3.])
b = torch.tensor([4., 5., 6.])

# Result: scalar (dot product)
print("Vector × Vector:", torch.matmul(a, b))


# -------------------------------
# 🔹 2. Matrix × Vector
# -------------------------------
A = torch.tensor([[1., 2., 3.],
                  [4., 5., 6.]])

v = torch.tensor([1., 2., 3.])

# Result: vector
print("Matrix × Vector:\n", torch.matmul(A, v))


# -------------------------------
# 🔹 3. Matrix × Matrix
# -------------------------------
A = torch.tensor([[1., 2.],
                  [3., 4.]])

B = torch.tensor([[5., 6.],
                  [7., 8.]])

# Result: matrix
print("Matrix × Matrix:\n", torch.matmul(A, B))


# -------------------------------
# 🔹 4. Batch Matrix Multiplication (3D tensors)
# -------------------------------
A = torch.rand(2, 2, 3)  # (batch=2, 2x3)
B = torch.rand(2, 3, 4)  # (batch=2, 3x4)

# Result: (2, 2, 4)
print("Batch MatMul shape:", torch.matmul(A, B).shape)


# -------------------------------
# 🔹 5. Using @ Operator (shortcut)
# -------------------------------
A = torch.tensor([[1., 2.],
                  [3., 4.]])

B = torch.tensor([[5., 6.],
                  [7., 8.]])

print("Using @ operator:\n", A @ B)

Vector × Vector: tensor(32.)
Matrix × Vector:
 tensor([14., 32.])
Matrix × Matrix:
 tensor([[19., 22.],
        [43., 50.]])
Batch MatMul shape: torch.Size([2, 2, 4])
Using @ operator:
 tensor([[19., 22.],
        [43., 50.]])
