<a href="https://colab.research.google.com/github/sripilla/deep-learning-course-notes/blob/main/02_Tensors_and_Multidimensional_Arrays/03_tensor_attributes_restructuring.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch   # Import PyTorch library

# Create a tensor of size (3 rows, 4 columns)
# torch.rand() generates random numbers between 0 and 1
some_tensor = torch.rand(3, 4)

# Print the tensor values
print(some_tensor)

# Print the shape (dimensions) of the tensor → (rows, columns)
print(some_tensor.shape)   # Output: torch.Size([3, 4])

# Print the data type of the tensor
# Default is float32 (torch.float32)
print(some_tensor.dtype)

# Print the device where tensor is stored
# Usually 'cpu' unless moved to GPU
print(some_tensor.device)

tensor([[0.1839, 0.7072, 0.9801, 0.0430],
        [0.0454, 0.7039, 0.8744, 0.1392],
        [0.8235, 0.1207, 0.7511, 0.2448]])
torch.Size([3, 4])
torch.float32
cpu


In [11]:
import torch

# Creating a scalar tensor (0-dimensional tensor)
t1 = torch.tensor(4.)

# Prints the shape of the tensor
# Since it is a scalar, shape will be: torch.Size([])
print(t1.shape)

# Prints the number of dimensions (rank) of the tensor
# Scalar → 0 dimensions
print(t1.ndim)

# Prints the length of shape tuple
# Since shape is empty (), length = 0
print(len(t1.shape))

torch.Size([])
0
0


In [12]:
import torch

# Creating a 1D tensor (vector)
t2 = torch.tensor([1., 2, 3, 4])

# Prints the shape of the tensor
# Shape shows number of elements in each dimension
# Here: 4 elements → shape = torch.Size([4])
print(t2.shape)

# Prints the number of dimensions (rank)
# Vector → 1 dimension
print(t2.ndim)

# Prints the length of shape tuple
# Since shape = [4], length = 1
print(len(t2.shape))

torch.Size([4])
1
1


In [13]:
import torch

# Creating a 2D tensor (matrix)
# It has 3 rows and 2 columns
t3 = torch.tensor([[5., 6],
                   [7, 8],
                   [9, 10]])

# Prints the tensor (matrix form)
print(t3)

# Prints number of dimensions (rank)
# Matrix → 2 dimensions (rows and columns)
print(t3.ndim)

# Prints length of shape tuple
# Shape = (3, 2) → 2 values → length = 2
print(len(t3.shape))


tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])
2
2


In [14]:
import torch

# Creating a 3D tensor
# Structure:
# 2 blocks (or matrices)
# Each block has 2 rows and 3 columns
t4 = torch.tensor([
    [[11, 12, 13],
     [13, 14, 15]],

    [[15, 16, 17],
     [17, 18, 19]]
])

# Prints the full 3D tensor
print(t4)

# Prints number of dimensions (rank)
# 3D tensor → 3 dimensions
print(t4.ndim)

# Prints length of shape tuple
# Shape = (2, 2, 3) → length = 3
print(len(t4.shape))

tensor([[[11, 12, 13],
         [13, 14, 15]],

        [[15, 16, 17],
         [17, 18, 19]]])
3
3


In [15]:
import torch

# Creating a 2D tensor (matrix)
# Shape = (3, 4) → 3 rows, 4 columns
t = torch.tensor([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

# Print original tensor
print(t)

# -------------------------------
# 🔹 Reshape (does NOT modify original tensor)
# Changes shape from (3,4) → (6,2)
# Total elements must remain same (3*4 = 6*2 = 12)
print(t.reshape(6, 2))

# -------------------------------
# 🔹 Resize (modifies tensor IN-PLACE)
# Changes shape to (2,6)
# ⚠️ Dangerous: may change data layout or add garbage values
print(t.resize_(2, 6))

# -------------------------------
# 🔹 Transpose
# Swaps dimensions (rows ↔ columns)
# (2,6) → (6,2) after resize
print(t.transpose(1, 0))




tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12]])
tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])
tensor([[ 1,  7],
        [ 2,  8],
        [ 3,  9],
        [ 4, 10],
        [ 5, 11],
        [ 6, 12]])
